---
- name: Clean
  hosts: all
  vars_files:
    - .vars/vars.yaml
  vars:
    authentik_home: /usr/local/authentik
    acme_home: /usr/local/acme
    traefik_home: /usr/local/traefik
  tasks:
    - name: Traefik files
      ansible.builtin.file:
        path: "{{ traefik_home }}"
        state: absent

    - name: Docker stop
      community.docker.docker_compose_v2:
        project_src: "docker-compose.yml"
        state: stopped
      ignore_errors: true

    - name: ACME dir
      ansible.builtin.file:
        path: "{{ acme_home }}"
        state: absent

    - name: ACME install
      ansible.builtin.file:
        path: "acme.sh"
        state: absent
