---
- name: Install
  hosts: all
  vars:
    authentik_dir: /usr/local/authentik
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Authentik dir
      ansible.builtin.file:
        path: "{{ authentik_dir }}"
        state: directory
        mode: "0755"

    - name: Authentik env
      ansible.builtin.shell:
        chdir: "{{ authentik_dir }}"
        executable: /bin/bash
        cmd: |
          echo "PG_PASS=$(openssl rand -base64 36 | tr -d '\n')" >> .env
          echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 60 | tr -d '\n')" >> .env
          echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> .env
        creates: "{{ authentik_dir }}/.env"

    - name: Authentik docker yaml
      ansible.builtin.get_url:
        url: https://goauthentik.io/docker-compose.yml
        dest: "{{ authentik_dir }}"

    - name: Authentik start
      community.docker.docker_compose_v2:
        project_src: "{{ authentik_dir }}"
